### ISSUE TITLE
Support the use of an external Markdown file instead of using markdown inside html

### ISSUE THREAD

**Issue by fegemo** [aaronpowell/bespoke-markdown#2]
Hi,

I'd like to know if it's ok to work on a feature to support the use of an external Markdown file to contain the whole presentation instead of supporting the use of markdown for the content of the slides.

My motivation is to have the full content of the bespoke presentation in Markdown format so we can, for example, use it as README.md and make the content of the presentation available as both a bespoke presentation and a README.md for access through GitHub, for example.

I'm inspired by the [markdown plugin for revealjs](https://github.com/hakimel/reveal.js/blob/master/plugin/markdown/markdown.js), which allows exactly that. For example, I created a presentation using revealjs + markdown plugin to achieve that:
- a revealjs presentation: http://fegemo.github.io/talk-es6/
- the github repo for that presentation: https://github.com/fegemo/talk-es6

**Comment by aaronpowell** [comment]
Sounds like a good idea!
